services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  IchHabRecht\ContentDefender\:
    resource: '../Classes/*'

  IchHabRecht\ContentDefender\Listener\ModifyNewContentElementWizardItems:
    tags:
      - name: event.listener
        identifier: 'IchHabRecht/ContentDefender/new-content-element-wizard'
